### ISSUE TITLE
I get error in Laravel 5.5 and 5.4

### ISSUE THREAD

**Issue by ferbj** [Clystnet/Vtiger#3]
I got this error in Laravel 5.5 
![image](https://user-images.githubusercontent.com/12809233/41747667-67720d36-7574-11e8-9700-9c13b3e902aa.png)
and Laravel 5.4 the same 
![image](https://user-images.githubusercontent.com/12809233/41747730-a78059be-7574-11e8-90c9-2f94d8c4e591.png)

i want know the reason of the issue becouse if i get loggin with the url 
i get success 
![image](https://user-images.githubusercontent.com/12809233/41747788-db33feaa-7574-11e8-9e05-771e56e9b178.png)
thank you for your help

**Comment by Chris-Pratt-Clystnet** [comment]
Make sure you have updated your config file to match the one in the readme.

It is most likeley the case that you havnt got the max_retries entry set in the config.

**Comment by ferbj** [comment]
Chris thats my file of configuration 
![image](https://user-images.githubusercontent.com/12809233/41802613-9ffd380a-7647-11e8-85da-a547eebddbaf.png)
i think that is correct i not understand why return this error.

**Comment by ferbj** [comment]
Chris thats my file config look that 

![image](https://user-images.githubusercontent.com/12809233/41802665-04124e16-7648-11e8-88d1-5b9344f97f6b.png)

i not understand why not working..

**Comment by Shadow2004** [comment]
Ok so try increasing your max tries up to say 100 and see if that helps.

Bit of sub text as we have found that some times on the login and get tokens routes the API didn't come back with a response so that loop is in there to try and deal with that problem.

Also if what I said doesn't work could you dump out the bit of code below inside the loop at the end of it so I can see what the API is responding with.

```php
die(var_dump(
    $this->_processResponse($response), 
    json_decode($response->getBody()), 
    json_decode($response->getBody()->getContents())
));
```

**Comment by Chris-Pratt-Clystnet** [comment]
Ok so try increasing your max tries up to say 100 and see if that helps.

Bit of sub text as we have found that some times on the login and get tokens routes the API didn't come back with a response so that loop is in there to try and deal with that problem.

Also if what I said doesn't work could you dump out the bit of code below inside the loop at the end of it so I can see what the API is responding with.

```php
die(var_dump(
    $this->_processResponse($response), 
    json_decode($response->getBody()), 
    json_decode($response->getBody()->getContents())
));
```

**Comment by ferbj** [comment]
Hello Chris i have the same issue 
look that 
![image](https://user-images.githubusercontent.com/12809233/41862446-889447de-7869-11e8-91ba-623ae583b14b.png)
i make the changes as you told writed.. lines above
![image](https://user-images.githubusercontent.com/12809233/41862512-b4aea5d0-7869-11e8-9589-f0677654d396.png)
tell me this happend if i have a virtualhost in my local computer? or is not a problem?..
 thank you..

**Comment by ferbj** [comment]
If i change in the construct the try catch to true,http errors and verify. 
i get error 406 on response. 
![image](https://user-images.githubusercontent.com/12809233/41863665-17ef1370-786d-11e8-8050-8b6a0a087afb.png)

![image](https://user-images.githubusercontent.com/12809233/41863685-2e5c5564-786d-11e8-8662-86974aa637d8.png)
now i do the var_dump in processResponse i have the same error of image below

**Comment by Chris-Pratt-Clystnet** [comment]
Ok don't change that setting as that turns on SSL certificate verification.

With the die var_dump remove the "$loginResult ="  of the front then run the code.
What this will do is dump to your screen the output of that request so i can debug what is happening.

**Comment by Chris-Pratt-Clystnet** [comment]
Yes that is a very good idea but not sure when i will have time to add that in so if some one feels like putting a pull request in for that i would be most appreciative.

**Comment by Chris-Pratt-Clystnet** [comment]
@ferbj are you still having issues or can i close this issue ?
